name: Docker Image CI

on:
  push:
    tags: "v*"
    branches: master

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2
      - uses: docker/build-push-action@v1.1.1
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}
          repository: trenchdevs/trenchdevs
          tag_with_ref: true
          tag_with_sha: true
          tags: latest
          push: true

